In [1]:
import pandas as pd 
import numpy as np

In [64]:
df = pd.read_csv('data1.csv')
df

S/no Country   Age   Salary Purchased
0     1   India  44.0  44000.0       yes
1     2  Russia  63.0  55605.0        no
2     3  Israel  38.0  42325.0       yes
3     4   India  41.0      NaN        no
4     5  Russia  65.0  63254.0       yes
5     6  Israel   NaN  12548.0       yes
6     7   India  28.0  96523.0        no
7     8  Russia  39.0      NaN        no
8     9  Israel   NaN  66322.0       yes
9    10   India  63.0  75415.0        no

In [65]:
x = df[['Country','Age','Salary']].values
x

array([['India', 44.0, 44000.0],
       ['Russia', 63.0, 55605.0],
       ['Israel', 38.0, 42325.0],
       ['India', 41.0, nan],
       ['Russia', 65.0, 63254.0],
       ['Israel', nan, 12548.0],
       ['India', 28.0, 96523.0],
       ['Russia', 39.0, nan],
       ['Israel', nan, 66322.0],
       ['India', 63.0, 75415.0]], dtype=object)

In [75]:
y = df[['Purchased']].values
y

array([['yes'],
       ['no'],
       ['yes'],
       ['no'],
       ['yes'],
       ['yes'],
       ['no'],
       ['no'],
       ['yes'],
       ['no']], dtype=object)

In [27]:
from sklearn.impute import SimpleImputer

In [21]:
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')

In [32]:
imputer = imputer.fit(x[:,1:3])

In [66]:
x[:,1:3] = imputer.transform(x[:,1:3])
x

array([['India', 44.0, 44000.0],
       ['Russia', 63.0, 55605.0],
       ['Israel', 38.0, 42325.0],
       ['India', 41.0, 56999.0],
       ['Russia', 65.0, 63254.0],
       ['Israel', 47.625, 12548.0],
       ['India', 28.0, 96523.0],
       ['Russia', 39.0, 56999.0],
       ['Israel', 47.625, 66322.0],
       ['India', 63.0, 75415.0]], dtype=object)

In [69]:
from sklearn.preprocessing import LabelEncoder

In [70]:
labelx = LabelEncoder()

In [71]:
x[:,0] = labelx.fit_transform(x[:,0])
x

array([[0, 44.0, 44000.0],
       [2, 63.0, 55605.0],
       [1, 38.0, 42325.0],
       [0, 41.0, 56999.0],
       [2, 65.0, 63254.0],
       [1, 47.625, 12548.0],
       [0, 28.0, 96523.0],
       [2, 39.0, 56999.0],
       [1, 47.625, 66322.0],
       [0, 63.0, 75415.0]], dtype=object)

In [77]:
labely = LabelEncoder()

In [89]:
y = labely.fit_transform(y)
y

C:\Users\goura\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 0, 1, 0, 1, 1, 0, 0, 1, 0])

In [72]:
from sklearn.preprocessing import OneHotEncoder

In [73]:
hotx = OneHotEncoder()

In [74]:
x = hotx.fit_transform(df.Country.values.reshape(-1,1)).toarray()
x

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [82]:
from sklearn.model_selection import train_test_split

In [84]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state = 0)

In [85]:
x_train

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [86]:
x_test

array([[0., 1., 0.],
       [0., 1., 0.]])

In [91]:
y_train

array([[1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1]], dtype=object)

In [88]:
y_test

array([[1],
       [1]], dtype=object)

In [92]:
from sklearn.preprocessing import StandardScaler

In [94]:
scx = StandardScaler()

In [95]:
x_train = scx.fit_transform(x_train)

In [97]:
x_test = scx.transform(x_test)

In [98]:
x_train

array([[-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        ,  2.64575131, -0.77459667]])

In [99]:
x_test

array([[-1.        ,  2.64575131, -0.77459667],
       [-1.        ,  2.64575131, -0.77459667]])

In [106]:
y_train = scx.fit_transform(y_train)

In [110]:
y_test = scx.transform(y_test)

In [111]:
y_train

array([[ 1.29099445],
       [-0.77459667],
       [-0.77459667],
       [-0.77459667],
       [-0.77459667],
       [-0.77459667],
       [ 1.29099445],
       [ 1.29099445]])

In [112]:
y_test

array([[1.],
       [1.]])